dist: bionic

language: rust
rust:
  - 1.42.0

before_install:
  - sudo apt-get install gnupg
  - sudo apt autoremove
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update

install:
  - sudo apt-get install -y mongodb-org

before_script:
  - sudo systemctl daemon-reload
  - sleep 10
  - sudo systemctl start mongod
  - sleep 20
  - mongo todo --eval 'db.todo.find();'

script:
  - cargo build --verbose --all
  - sh test.sh
  - sudo systemctl stop mongod
  - sudo apt-get purge mongodb-org*
  - sudo rm -r /var/log/mongodb
  - sudo rm -r /var/lib/mongodb
