dist: bionic

language: rust
rust:
    - 1.42.0

services:
    - mongodb

before_script:
    - apt install mongodb-clients
    - sleep 20
    - mongo todo --eval 'db.todo.find();'

script:
    - cargo build --verbose --all
    - sh test.sh
